title: Default Configuration - Blablador

coding:
  servers:
    id-server:
      host: localhost
      port: 8080
  config:
    annotations:
      diagnosen:
        - id-server: /inception/lookup_icd10?q={text}
      medikationen:
        - id-server: /inception/lookup_sct?q={text}
    response:
      id-server:
        parse:
        restrict: [ ]
    get_all: false
  ignore_fields:
    - id

pydantic-ai:
  model:
    implementation: openai.OpenAIChatModel
    name: alias-large
  provider:
    implementation: openai.OpenAIProvider
    url: https://api.helmholtz-blablador.fz-juelich.de/v1/
    api_key:

pydantic:
  TextAnnotationen:
    title: TextAnnotationen
    type: object
    properties:
      diagnosen:
        type: array
        items:
          type: object
          title: Diagnose
          properties:
            text:
              type: string
              title: |-
                Die konkrete Referenz der Diagnose im Text.
            condition_after:
              type: bool
              title: |-
                Gibt an, ob es ein Zustand nach einem Eingriff ist (z.B.: 'Zustand nach Konisation').
                Antworte hier lediglich mit 'true' für 'ja' oder 'false' für 'nein'.
            is_old:
              type: bool
              title: |-
                Gibt an, ob es eine alte, sehr lange zurückliegende Diagnose ist (z.B.: 'Röteln im Kindesalter').
                Antworte hier lediglich mit 'true' für 'ja' oder 'false' für 'nein'.
            is_family:
              type: bool
              title: |-
                Gibt an, ob es eine Anamnese in der Familie ist (z.B.: 'Brustkrebs bei der Mutter').
                Antworte hier lediglich mit 'true' für 'ja' oder 'false' für 'nein'.
      medikationen:
        type: array
        items:
          type: object
          title: Medikation
          properties:
            text:
              type: string
              title: Die konkrete Referenz einer Medikation oder eines Wirkstoffs im Text.

prompt: |-
  Du bist ein medizinischer Dokumentar.
  Aus den Texten, die dir gegeben werden extrahierst du die `TextAnnotationen`.