title: Default Configuration

coding:
  servers:
    id-server:
      host: localhost
      port: 8080
  config:
    diagnosen:
      - id-server: /inception/lookup_icd10?q={text}
    medikationen:
      - id-server: /inception/lookup_sct?q={text}

pydantic-ai:
  model: openai.OpenAIChatModel
  provider: openai.OpenAIProvider
  api_key:

pydantic:
  TextAnnotationen:
    title: TextAnnotationen
    type: object
    properties:
      diagnosen:
        type: array
        items:
          type: object
          title: Diagnose
          properties:
            text:
              type: string
              title: Die konkrete Referenz der Diagnose im Text.
      medikationen:
        type: array
        items:
          type: object
          title: Medikation
          properties:
            text:
              type: string
              title: Die konkrete Referenz einer Medikation oder eines Wirkstoffs im Text.

prompt: |-
  Du bist ein medizinischer Dokumentar.
  Aus den Texten, die dir gegeben werden extrahierst du die `TextAnnotationen`.